# Generated by Django 3.1.5 on 2021-01-30 19:02

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.FileField(upload_to=photos.models.user_directory_path),
        ),
    ]
