# Generated by Django 3.1.5 on 2021-01-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url_one', models.CharField(blank=True, max_length=512)),
                ('image_url_two', models.CharField(blank=True, max_length=512)),
                ('image_url_three', models.CharField(blank=True, max_length=512)),
                ('image_url_four', models.CharField(blank=True, max_length=512)),
                ('image_url_five', models.CharField(blank=True, max_length=512)),
                ('image_url_six', models.CharField(blank=True, max_length=512)),
                ('username', models.CharField(max_length=128)),
            ],
        ),
    ]
