# Generated by Django 3.1.5 on 2021-01-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one', models.CharField(max_length=256)),
                ('user_two', models.CharField(max_length=256)),
                ('user_one_auth', models.BooleanField(blank=True)),
                ('user_two_auth', models.BooleanField(blank=True)),
            ],
        ),
    ]
